services:
  app:
    env_file: '.env.development'
    build: ./portal-api
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./portal-api:/app
    depends_on:
      - db
    command: bash -c 'rails s -b 0.0.0.0 -p 3001'

  db:
    image: postgres:16.0
    env_file: '.env.development'
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
