---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customer":
    post:
      summary: Creates a customer
      tags:
      - Customers
      parameters: []
      responses:
        '200':
          description: customer created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
    delete:
      summary: Deletes a Customer
      tags:
      - Customers
      security:
      - auth_token: []
      responses:
        '200':
          description: customer deleted
        '404':
          description: customer not found
  "/api/v1/customer/sign_in":
    post:
      summary: Sign in a customer
      tags:
      - Customers
      parameters: []
      responses:
        '200':
          description: customer signed in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/customers/{id}":
    get:
      summary: Retrieves a customer
      tags:
      - Customers
      security:
      - auth_token: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: customer found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '401':
          description: unauthorized
    put:
      summary: Updates a customer
      tags:
      - Customers
      security:
      - auth_token: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: customer updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
  "/api/v1/internal/simulations":
    get:
      summary: Retrieves simulations
      tags:
      - Internal Simulations
      security:
      - internal_key: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: Api-Internal-Key
        in: header
        schema:
          type: string
      responses:
        '200':
          description: simulations found
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        customer_id:
                          type: integer
                        electricity_bill:
                          type: number
                        power:
                          type: number
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        self_link:
                          type: string
        '401':
          description: unauthorized
  "/api/v1/internal/simulations/{id}":
    get:
      summary: Retrieves a simulation
      tags:
      - Internal Simulations
      security:
      - internal_key: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Api-Internal-Key
        in: header
        schema:
          type: string
      responses:
        '200':
          description: simulation found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer_id:
                    type: integer
                  electricity_bill:
                    type: number
                  power:
                    type: number
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  self_link:
                    type: string
                  download_link:
                    type: string
                  chosen_generators:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        uuid:
                          type: string
                        name:
                          type: string
                        price:
                          type: number
                        panels:
                          type: integer
                        power:
                          type: number
                        image_url:
                          type: string
        '401':
          description: unauthorized
        '404':
          description: simulation not found
  "/api/v1/simulations":
    get:
      summary: Retrieves simulations
      tags:
      - Customers
      security:
      - auth_token: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: customer simulations found
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        customer_id:
                          type: integer
                        electricity_bill:
                          type: number
                        power:
                          type: number
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        self_link:
                          type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
        '401':
          description: unauthorized
    post:
      summary: Creates a simulation
      tags:
      - Simulations
      security:
      - auth_token: []
      parameters: []
      responses:
        '200':
          description: simulation created
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation:
                    type: object
                    properties:
                      id:
                        type: integer
                      customer_id:
                        type: integer
                      electricity_bill:
                        type: number
                      power:
                        type: number
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      self_link:
                        type: string
                      download_link:
                        type: string
                      chosen_generators:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            uuid:
                              type: string
                            name:
                              type: string
                            price:
                              type: number
                            panels:
                              type: integer
                            power:
                              type: number
                            image_url:
                              type: string
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                electricity_bill:
                  type: float
              required:
              - electricity_bill
  "/api/v1/simulations/{id}":
    get:
      summary: Retrieves a simulation
      tags:
      - Simulations
      security:
      - auth_token: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: simulation found
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation:
                    type: object
                    properties:
                      id:
                        type: integer
                      customer_id:
                        type: integer
                      electricity_bill:
                        type: number
                      power:
                        type: number
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      self_link:
                        type: string
                      download_link:
                        type: string
                      chosen_generators:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            uuid:
                              type: string
                            name:
                              type: string
                            price:
                              type: number
                            panels:
                              type: integer
                            power:
                              type: number
                            image_url:
                              type: string
        '404':
          description: simulation not found
        '401':
          description: unauthorized
  "/api/v1/simulations/{id}/download":
    get:
      summary: Downloads a simulation as PDF
      tags:
      - Simulations
      security:
      - auth_token: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: simulation downloaded
        '404':
          description: simulation not found
        '401':
          description: unauthorized
components:
  securitySchemes:
    auth_token:
      type: apiKey
      name: Authorization
      in: header
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
